BOT_SYMBOL=SNX/EUR
BOT_ARGS=--timeframe 5m --fast 7 --slow 18 --sl 0.015 --tp 0.04 --safety-buffer 0.1 --startup-delay 100 --trailing-sl-pct 200 --volume-factor 1.2 --breakeven-pct 0.008 --partial-tp-fraction 0.5 --breakeven --htf-timeframe 1h --htf-fast 21 --htf-slow 55 --sma200-filter --slope-filter
