BOT_SYMBOL=SNX/EUR
BOT_ARGS=--timeframe 5m --fast 21 --slow 55 --sl 0.015 --tp 0.075 --safety-buffer 0.1 --startup-delay 100 --trailing-sl-pct 0.03 --volume-factor 1.5 --breakeven-pct 0.008 --partial-tp-fraction 0.5 --breakeven --htf-timeframe 1h --htf-fast 21 --htf-slow 55 --sma200-filter --slope-filter --volume-filter
